apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tds-codemod
  description: A codemod for upgrading from TDS v1 to v2
  tags:
    - node
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=tds-codemod
    backstage.io/techdocs-ref: dir:docs
    github.com/project-slug: telus/tds-codemod
  links:
    - url: https://github.com/telus/tds-codemod
      title: Website
      icon: web
spec:
  type: service
  lifecycle: experimental
  owner: telus
  system: digital
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tds-codemod
  description: A codemod for upgrading from TDS v1 to v2
  tags:
    - null
    - null
    - node
  annotations:
    github.com/project-slug: telus/tds-codemod
  links:
    - url: https://github.com/telus/tds-codemod
      title: API Spec
      icon: code
    - url: https://github.com/telus/tds-codemod
      title: Website
      icon: web
spec:
  type: openapi
  lifecycle: experimental
  owner: digital
